name: On Release, deploying to Prod
on:
  release:
    types: [published]
  run-build-and-deploy:
    uses: octopusden/octopus-base/.github/workflows/common-py-2-3-build-deploy.yml@main
    with:
      process_env: Prod
    secrets: inherit
